---
title: "Analysis E1A Inner Speech Talk and Type"
author: "Matt"
date: "5/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

# Load Libraries

```{r}
library(papaja)
library(TalkTyping)
library(dplyr)
library(Crump)
library(xtable)
library(ggplot2)
library(ggpubr)
```

# E1A IKSI Analysis

```{r}
#load E1A data
E1_data <- talk_type_E1A_data

# IKSI analysis

E1_data <- E1_data %>%
            mutate(subject = as.factor(subject)) %>%
            filter(errors == 1,
                   iksis < 5000,
                   LetterType != "Space") %>%
            group_by(subject,linguistic_unit,LetterType) %>%
            summarise(mean_iksi = mean(modified_recursive_moving(iksis)$restricted),
                      prop_removed = modified_recursive_moving(iksis)$prop_removed)
                  
E1_aov_out <- aov(mean_iksi ~ linguistic_unit*LetterType + 
                    Error(subject/(linguistic_unit*LetterType)), E1_data)

knitr::kable(xtable(summary(E1_aov_out)))

E1_apa_print <- apa_print(E1_aov_out)
E1_means <- model.tables(E1_aov_out,"means")

```

```{r, fig.width=3, fig.height=3}
E1A_iksi_table <- E1_data %>%
              group_by(linguistic_unit,LetterType) %>%
              summarize(mIKSI = mean(mean_iksi),
                        sem = sd(mean_iksi)/sqrt(length(mean_iksi)))

levels(E1A_iksi_table$linguistic_unit) <- c("Say Letter", "Say Word")

E1A_graph_iksi <- ggplot(E1A_iksi_table, aes(x=linguistic_unit,
                                             y=mIKSI, 
                                             group=LetterType,
                                             fill=LetterType))+
  geom_bar(stat="identity",position="dodge")+
  geom_errorbar(aes(ymin=mIKSI-sem,
                    ymax=mIKSI+sem), width=.1,
                linetype="solid", position=position_dodge(.9))+
  scale_fill_grey(start = 0.6, end = 0.8, na.value = "red",
  aesthetics = "fill")+
  theme_classic(base_size=12)+
  theme(legend.position = "top",
        legend.title = element_blank())+
  ylab("Mean IKSI (ms)")+
  xlab("Letter position")

knitr::kable(E1A_iksi_table)
E1A_graph_iksi

```

## accuracy

```{r}

# Accuracy

E1acc_data <- talk_type_E1A_data


E1acc_data <- E1acc_data %>%
                mutate(subject = as.factor(subject)) %>%
                filter(LetterType != "Space") %>%
                group_by(subject, linguistic_unit, LetterType) %>%
                summarise(mean_acc = mean(errors))
                  
E1acc_aov_out <- aov(mean_acc ~ linguistic_unit*LetterType + Error(subject/(linguistic_unit*LetterType)), E1acc_data)

E1acc_apa_print <- apa_print(E1acc_aov_out)
E1acc_means <- model.tables(E1acc_aov_out,"means")

knitr::kable(xtable(summary(E1acc_aov_out)))

```

```{r, fig.width=3, fig.height=3}
E1A_acc_table <- E1acc_data %>%
              group_by(linguistic_unit,LetterType) %>%
              summarize(mAcc = mean(mean_acc),
                        sem = sd(mean_acc)/sqrt(length(mean_acc)))

levels(E1A_acc_table$linguistic_unit) <- c("Say Letter", "Say Word")

E1A_graph_acc <- ggplot(E1A_acc_table, 
                         aes(x=linguistic_unit,
                             y=mAcc, 
                             group=LetterType,
                             fill=LetterType))+
  geom_bar(stat="identity",position="dodge")+
  geom_errorbar(aes(ymin=mAcc-sem,
                    ymax=mAcc+sem), width=.1,
                linetype="solid", position=position_dodge(.9))+
  scale_fill_grey(start = 0.6, end = 0.8, na.value = "red",
  aesthetics = "fill")+
  theme_classic(base_size=12)+
  theme(legend.position = "top",
        legend.title = element_blank())+
  ylab("Mean Accuracy")+
  xlab("Letter position")+
  coord_cartesian(ylim=c(.8,1))

knitr::kable(E1A_acc_table)
E1A_graph_acc
```

# Figure 1

```{r}
ggarrange(E1A_graph_iksi,E1A_graph_acc)

```



# Demographic information

```{r}

E1A_dmg <- talk_type_E1A_dmg
proportion_word <- E1A_dmg %>%
                    group_by(InnerVoice) %>%
                    summarize(p_word = length(InnerVoice)/dim(E1A_dmg)[1])

inner_voice_props<-c(
  round(proportion_word[proportion_word$InnerVoice=="Words",]$p_word, digits=2),
round(proportion_word[proportion_word$InnerVoice=="Letters",]$p_word,digits=2),
round(proportion_word[proportion_word$InnerVoice=="undefined",]$p_word,digits=2))

```


# Save all

```{r}
save.image(file="E1A_workspace.RData")
```

